language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: Yr/vnT3lvp0dwmiAAzrf0PcwtN2yE+Ho/Sk09anp/L8fXZC2ICGDl/EzrNKG/FLvs+HtKu2+WsczyHe8w+CeoWwbabsblygSzRpE0+/rN0LCGaXsb+qFZIX20p0rTf3tQMjzexvl+H8R8Sbreb7tOAJiWBNA25DxN/1rsPcYFKQ13C/FNB4PLgQprkFSyL4T/irxxZ2u4xnZLHStOC9t1r2ZFW/b9Zc0TMDuEshFjZnSuIykomspwA8CIKP0tYcT2O30F80pBGLPAzoFU1eOEkBmaNmu+NjudqwvkMXQa2RjLGWroKrIS2uXC92R/1578OCVOWTbqOM/xVFtqu2QN67Um/GmipZYR7hSntq+SYsf2uFN4YZz+e3/dyzxUFgrQ43D4UaHuaCjF1GiTiLKmoyTr44QTPXgzS1Z6F1M1bd/WqwY9aOyV27IdUnUqARLQSvSKiTIPS67Lg3YmolA7dsQhUky0534aUvu9yRwIVY0O0RcJPUAvb5JnRlamGXi/NG9A9/OU23FqsHeJlBxno+4XPJLnGZWyd77U545TzqxjWzhnTiHCB3qctusV2Ghf8Jdr7HZBL2OE61G+jPeZ1bcHXE5Kqk/bz7UqpO8f+MebxYwlpSv0pxH3fNHpZMz7DfSaBbHMIvd1CCkq1YpGRUlJY45naZN5Gwz9x3za7M=
  skip_cleanup: true
  file:
    - bin/ecsedit-linux
    - bin/ecsedit-macos
    - bin/ecsedit-win.exe
  on:
    repo: gumieri/ecsedit
    tags: true
